--- faster-recipes.lua

local debug_errors = false

local recipe_speed_multipliers = {
    ["stone-brick"] = 2,
    ["bricks-to-stone"] = 2,
    ["stone-to-gravel"] = 2,
    ["gravel-to-sand"] = 2,
    ["sand-washing"] = 2,
    ["extract-limestone-01"] = 3,
    ["cellulose-00"] = 3,
    ["saline-water"] = 4,
    ["gravel-saline-water"] = 4,
    ["clay"] = 2,
    ["soil"] = 2,
    ["muddy-sludge"] = 2,
    ["soil-separation-2"] = 2,
    ["sand-void-glass"] = 2,
    ["glass-1"] = 2,
    ["glass-2"] = 2,
    ["glass-3"] = 2,
    ["graphite"] = 2,
    ["syngas"] = 2,
    ["syngas2"] = 2,
    ["tar-refining"] = 2,
    ["pitch-refining"] = 2,
    ["coke-co2"] = 2,
    ["purest-nitrogen-void"] = 2,
    ["purest-nitrogen-gas"] = 2,
    ["hydrogen"] = 2,
    ["muddy-sludge-void-electrolyzer"] = 3,
    ["water-from-oxygen-and-hydrogen"] = 5,
    ["waste-water-void"] = 5,
    ["sulfur-void-water"] = 5,
    ["ash"] = 2,
    ["filtration-dirty-water"] = 2,
    ["formica"] = 2,
    ["calcium-carbide"] = 2,
    ["acetylene"] = 2,
    ["agar"] = 3,
    ["petri-dish"] = 2,
    ["petri-dish-bacteria"] = 3,
    ["rubber-01"] = 2,
    ["stopper-2"] = 2,
    ["shaft-mk01"] = 5,
    ["refined-concrete"] = 3,
    ["crushed-coal"] = 2,
    ["coke-coal"] = 2,
    ["warm-stone-brick-1"] = 4,
    ["warmer-stone-brick-1"] = 5,
    ["reheat-coke-gas"] = 2,
    ["reheat-outlet-gas-2"] = 2,
    ["minor-extract-gas-from-coalbed-3"] = 2,
    ["extract-gas-from-coalbed-3"] = 2,
    ["extract-gas-from-coalbed-4"] = 2,
    ["extract-methane-from-coalbed"] = 2,
    ["extract-methane-from-coalbed-2"] = 2,
    ["cool-steam-250-to-150"] = 3,
    ["cool-steam-500-to-250"] = 3,
    ["cool-steam-1000-to-500"] = 3,
    ["cool-steam-2000-to-1000"] = 3,
    ["cool-pressured-steam-2000-to-1000"] = 3,
    ["cool-pressured-steam-3000-to-2000"] = 3,
    ["cool-pressured-steam-4000-to-3000"] = 3,
    ["cool-pressured-steam-5000-to-4000"] = 3,
    -- metals:
    ["steel-plate"] = 2,
    ["iron-plate"] = 2,
    ["low-grade-smelting-iron"] = 2,
    ["copper-plate"] = 2,
    ["tin-plate-1"] = 2,
    ["tin-plate-2"] = 2,
    ["tin-plate-4"] = 2,
    ["zinc-plate-1"] = 2,
    ["lead-plate-1"] = 2,
    ["lead-plate-2"] = 2,
    ["titanium-plate-1"] = 2,
    ["titanium-plate-2"] = 2,
    ["nickel-plate-2"] = 2,
    ["grade-1-iron-crush"] = 2,
    ["grade-2-iron"] = 2,
    ["iron-ore-dust"] = 2,
    ["molten-iron-05"] = 2,
    ["grade-2-copper"] = 2,
    ["grade-1-copper-crush"] = 2,
    ["grade-3-copper"] = 2,
    ["copper-rejects-recrush"] = 2,
    ["grade-4-copper"] = 2,
    ["classify-low-grade"] = 2,
    ["wash-coper-low-dust"] = 2,
    ["low-grade-smelting-copper"] = 2,
    ["molten-copper-04"] = 2,
    ["grade-1-tin"] = 2,
    ["grade-2-crush-tin"] = 2,
    ["grade-3-tin"] = 3,
    ["tin-ore-rejects"] = 3,
    ["wash-grade-3-tin"] = 3,
    ["ball-grade-4-tin"] = 3,
    ["grade-1-zinc"] = 2,
    ["grade-1-lead"] = 2,
    ["grade-1-ti"] = 2,
    ["grade-2-ti-crush"] = 2,
    ["grade-3-ti"] = 2,
    ["ti-rejects-recrush"] = 2,
    ["grade-4-ti"] = 2,
    ["ti-enriched-dust"] = 2,
    ["sb-grade-01"] = 2,
    ["sb-grade-02"] = 2,
    ["sb-grade-03"] = 2,
    ["sb-grade-04"] = 2,
    ["sb-oxide-01"] = 2,
    ["sb-crushed"] = 2,
    ["sb-dust"] = 2,
    ["sb-pulp-02"] = 2,
    ["grade-1-nickel"] = 2,
    ["grade-3-nickel"] = 2,
    ["grade-2-nickel-recrush"] = 2,
    ["grade-4-chromite"] = 2,
    ["chromite-rejects-processing"] = 2,
    ["tier-2-chromite-sand"] = 2,
    ["chromium-01"] = 2,
    ["solder-0"] = 3,
    ["molten-solder-0"] = 2,
    ["duralumin-1"] = 2,
    ["vitreloy"] = 2,
    ["fenxsb-alloy-2"] = 4,
    ["pbsb-alloy"] = 2,
    -- alien life:
    {names={"bio-sample", "bio-sample-icd"}, mult=2},
    {names={"Moss-1", "Moss-1-chlorinated", "Moss-1-without-sludge", "Moss-1-without-sludge-for-real"}, mult=4},
    {names={"Moss-2", "Moss-2-chlorinated", "Moss-2-without-sludge", "Moss-2-without-sludge-for-real"}, mult=3.2},
    {names={"Moss-3", "Moss-3-chlorinated", "Moss-3-without-sludge", "Moss-3-without-sludge-for-real"}, mult=2.4},
    {names={"Moss-4", "Moss-4-chlorinated", "Moss-4-without-sludge", "Moss-4-without-sludge-for-real"}, mult=1.6},
    {names={"log1", "log2", "log3", "log3-cheap"}, mult=2},
    ["fiber-01"] = 5,
    ["fiber-dry-storage"] = 5,
    ["kicalk-fiber"] = 2,
    ["sap-01"] = 4,
    {names={"moondrop-1", "moondrop-1-cu"}, mult=4},
    {names={"moondrop-2", "moondrop-2-cu"}, mult=3.25},
    {names={"moondrop-3", "moondrop-3-cu"}, mult=2.5},
    {names={"moondrop-4", "moondrop-4-cu"}, mult=1.75},
    ["methane-co2"] = 2,
    ["methane-co2-with-lamp"] = 2,
    ["moondrop-co2"] = 2,
    {names={"seaweed-1", "seaweed-1-dry"}, mult=4},
    {names={"seaweed-2", "seaweed-2-dry"}, mult=3.25},
    {names={"seaweed-3", "seaweed-3-dry"}, mult=2.5},
    {names={"seaweed-4", "seaweed-4-dry"}, mult=1.75},
    {names={"vrauks-cocoon-1", "vrauks-cocoon-1-no-water", "vrauks-1", "vrauks-1-no-water"}, mult=4},
    {names={"vrauks-cocoon-2", "vrauks-cocoon-2-no-water", "vrauks-2", "vrauks-2-no-water"}, mult=3.25},
    {names={"vrauks-cocoon-3", "vrauks-cocoon-3-no-water", "vrauks-3", "vrauks-3-no-water"}, mult=2.5},
    {names={"vrauks-cocoon-4", "vrauks-cocoon-4-no-water", "vrauks-4", "vrauks-4-no-water"}, mult=1.75},
    {names={"full-render-vrauks", "full-render-vrauks-lard", "full-render-vrauks-laser", "full-render-vrauks-music"}, mult=2},
    ["phytoplankton"] = 3,
    ["jerky-to-phytoplankton"] = 2,
    {names={"breed-fish-1", "breed-fish-1-agressive-selection"}, mult=2},
    {names={"breed-fish-2", "breed-fish-2-agressive-selection"}, mult=1.66},
    {names={"breed-fish-3", "breed-fish-3-agressive-selection"}, mult=1.33},
    {names={"full-render-fish", "full-render-fish-lard", "full-render-fish-laser", "full-render-fish-music"}, mult=3},
    {names={"full-render-auogs", "full-render-auogs-lard", "full-render-auogs-laser", "full-render-auogs-music", "ex-used-auog", "ex-used-auog-lard", "ex-used-auog-laser", "ex-used-auog-music"}, mult=5},
    {names={"ralesia-1", "ralesia-1-hydrogen-burn"}, mult=4},
    {names={"ralesia-2", "ralesia-2-hydrogen-burn"}, mult=3},
    {names={"ralesia-3", "ralesia-3-hydrogen-burn"}, mult=2},
    ["cottongut-mature-basic-01"] = 3,
    {names={"caged-cottongut-1", "caged-cottongut-1-cannibal"}, mult=2},
    {names={"caged-cottongut-2", "caged-cottongut-2-cannibal"}, mult=1.66},
    {names={"caged-cottongut-3", "caged-cottongut-3-cannibal"}, mult=1.33},
    {names={"full-render-cottongut", "full-render-cottongut-lard", "full-render-cottongut-laser", "full-render-cottongut-music"}, mult=3},
    {names={"fawogae-1", "fawogae-1-nitrogen"}, mult=3},
    {names={"fawogae-2", "fawogae-2-nitrogen"}, mult=2.5},
    {names={"fawogae-3", "fawogae-3-nitrogen"}, mult=2},
    {names={"fawogae-4", "fawogae-4-nitrogen"}, mult=1.5},
    {names={"ulric-manure-1", "ulric-manure-2", "ulric-manure-3", "ulric-manure-4"}, mult=3},
    {names={"full-render-ulrics", "full-render-ulrics-lard", "full-render-ulrics-laser", "full-render-ulrics-music"}, mult=6},
    {names={"tuuphra-1", "tuuphra-1-fungicide"}, mult=3},
    {names={"tuuphra-2", "tuuphra-2-fungicide"}, mult=2.33},
    {names={"tuuphra-3", "tuuphra-3-fungicide"}, mult=1.66},
    ["arqad-filled-honeycomb-1"] = 2,
    ["arqad-filled-honeycomb-2"] = 1.66,
    ["arqad-filled-honeycomb-3"] = 1.33,
    {names={"korlex-1", "korlex-1-slowed"}, mult=2},
    {names={"korlex-2", "korlex-2-slowed"}, mult=1.5},
    {names={"korlex-3", "korlex-3-slowed"}, mult=1.25},
    {names={"full-render-kor", "full-render-kor-lard", "full-render-kor-laser", "full-render-kor-music"}, mult=4},
    {names={"zipir-eggs-1", "zipir-eggs-1-trits-gen"}, mult=2},
    {names={"zipir-eggs-2", "zipir-eggs-2-trits-gen"}, mult=1.66},
    {names={"zipir-eggs-3", "zipir-eggs-3-trits-gen"}, mult=1.33},
    {names={"zipir-eggs-4", "zipir-eggs-4-trits-gen"}, mult=1.05},
    {names={"zipir-a-1", "zipir-a-1-suicide"}, mult=2},
    {names={"zipir-a-2", "zipir-a-2-suicide"}, mult=1.8},
    {names={"zipir-a-3", "zipir-a-3-suicide"}, mult=1.6},
    {names={"zipir-a-4", "zipir-a-4-suicide"}, mult=1.4},
    {names={"zipir-a-5", "zipir-a-5-suicide"}, mult=1.2},
    {names={"full-render-zipir", "full-render-zipir-lard", "full-render-zipir-laser", "full-render-zipir-music"}, mult=2},
    {names={"xyhiphoe-1", "xyhiphoe-1-hot-cold"}, mult=2},
    {names={"xyhiphoe-2", "xyhiphoe-2-hot-cold"}, mult=1.66},
    {names={"xyhiphoe-3", "xyhiphoe-3-hot-cold"}, mult=1.33},
    {names={"full-render-xyhiphoe", "full-render-xyhiphoe-lard", "full-render-xyhiphoe-laser", "full-render-xyhiphoe-music"}, mult=3},
    ["yotoi-fruit-1"] = 2,
    {names={"yotoi-fruit-2", "yotoi-fruit-2-nutrient"}, mult=1.66},
    {names={"yotoi-fruit-3", "yotoi-fruit-3-nutrient"}, mult=1.33},
    {names={"yotoi-1", "yotoi-1-free-leaves"}, mult=4},
    {names={"yotoi-2", "yotoi-2-free-leaves", "yotoi-2-nutrient"}, mult=3},
    {names={"yotoi-3", "yotoi-3-free-leaves", "yotoi-3-nutrient"}, mult=2},
    {names={"rennea-1", "rennea-1-deadhead", "rennea-1-hydrophile"}, mult=5},
    {names={"rennea-2", "rennea-2-deadhead", "rennea-2-hydrophile"}, mult=3.33},
    {names={"rennea-3", "rennea-3-deadhead", "rennea-3-hydrophile"}, mult=2},
    {names={"grod-1", "grod-1-pressured", "grod-1-dry"}, mult=2},
    {names={"grod-2", "grod-2-pressured", "grod-2-dry"}, mult=1.66},
    {names={"grod-3", "grod-3-pressured", "grod-3-dry"}, mult=1.33},
    {names={"mukmoux-manure-1", "mukmoux-manure-2", "mukmoux-manure-3", "mukmoux-manure-4"}, mult=3},
    {names={"full-render-mukmoux", "full-render-mukmoux-lard", "full-render-mukmoux-laser", "full-render-mukmoux-music"}, mult=4},
    {names={"cadaveric-arum-1", "cadaveric-arum-1-soil", "cadaveric-arum-1-msa"}, mult=4},
    {names={"cadaveric-arum-2", "cadaveric-arum-2-soil", "cadaveric-arum-2-msa"}, mult=3},
    {names={"cadaveric-arum-3", "cadaveric-arum-3-soil", "cadaveric-arum-3-msa"}, mult=2},
    ["phagnot-mature-basic-01"] = 3,
    {names={"phagnot-1", "phagnot-1-kicalk"}, mult=2},
    {names={"phagnot-2", "phagnot-2-kicalk"}, mult=1.66},
    {names={"phagnot-3", "phagnot-3-kicalk"}, mult=1.33},
    {names={"full-render-phagnots", "full-render-phagnots-lard", "full-render-phagnots-laser", "full-render-phagnots-music"}, mult=5},
    {names={"arthurian-egg-1", "arthurian-egg-1-hot-stones"}, mult=1.5},
    {names={"arthurian-egg-2", "arthurian-egg-2-hot-stones"}, mult=1.33},
    {names={"arthurian-egg-3", "arthurian-egg-3-hot-stones"}, mult=1.16},
    ["arthurian-egg-incubation-01"] = 3,
    ["arthurian-grow-01"] = 3,
    ["arthurian-cannibalism"] = 3,
    {names={"arthurian-maturing-1", "arthurian-maturing-1-abacus"}, mult=1.5},
    {names={"arthurian-maturing-2", "arthurian-maturing-2-abacus"}, mult=1.33},
    {names={"arthurian-maturing-3", "arthurian-maturing-3-abacus"}, mult=1.16},
    {names={"full-render-arthurian", "full-render-arthurian-lard", "full-render-arthurian-laser", "full-render-arthurian-music"}, mult=4},
    {names={"dhilmos-1", "dhilmos-1-cover", "dhilmos-1-skimmer", "dhilmos-1-double-intake"}, mult=2},
    {names={"dhilmos-2", "dhilmos-2-cover", "dhilmos-2-skimmer", "dhilmos-2-double-intake"}, mult=1.66},
    {names={"dhilmos-3", "dhilmos-3-cover", "dhilmos-3-skimmer", "dhilmos-3-double-intake"}, mult=1.33},
    {names={"full-render-dhilmoss", "full-render-dhilmoss-lard", "full-render-dhilmoss-laser", "full-render-dhilmoss-music"}, mult=3},
    {names={"Scrondrix-Manure-1", "Scrondrix-Manure-2", "Scrondrix-Manure-3", "Scrondrix-Manure-4"}, mult=3},
    {names={"full-render-scrondrixs", "full-render-scrondrixs-lard", "full-render-scrondrixs-laser", "full-render-scrondrixs-music"}, mult=6},
    {names={"dingrits-1", "dingrits-1-training"}, mult=2},
    {names={"dingrits-2", "dingrits-2-training"}, mult=1.66},
    {names={"dingrits-3", "dingrits-3-training"}, mult=1.33},
    {names={"full-render-dingrits", "full-render-dingrits-lard", "full-render-dingrits-laser", "full-render-dingrits-music", "ex-used-dingrits", "ex-used-dingrits-lard", "ex-used-dingrits-laser", "ex-used-dingrits-music"}, mult=5},
    ["phadai-pup-1"] = 3,
    ["phadai-pup-2"] = 2.66,
    ["phadai-pup-3"] = 2.33,
    ["phadai-pup-4"] = 2,
    ["phadai-pup-5"] = 1.66,
    ["phadai-pup-6"] = 1.33,
    {names={"full-render-phadais", "full-render-phadais-lard", "full-render-phadais-laser", "full-render-phadais-music"}, mult=3},
    {names={"full-render-simik", "full-render-simik-lard", "full-render-simik-laser", "full-render-simik-music"}, mult=2},
    {names={"full-render-num", "full-render-num-lard", "full-render-num-laser", "full-render-num-music"}, mult=3},
    {names={"vonix-raising-1", "vonix-raising-1-cancer"}, mult=2},
    {names={"vonix-raising-2", "vonix-raising-2-cancer"}, mult=1.5},
    {names={"full-render-vonix", "full-render-vonix-lard", "full-render-vonix-laser", "full-render-vonix-music"}, mult=3},
    {names={"zungror-raising-1", "zungror-raising-1-with-funny-rock"}, mult=2},
    {names={"zungror-raising-2", "zungror-raising-2-with-funny-rock"}, mult=1.5},
    {names={"caged-xeno-1", "caged-xeno-1-dna-polymerase"}, mult=2},
    {names={"caged-xeno-2", "caged-xeno-2-dna-polymerase"}, mult=1.66},
    {names={"caged-xeno-3", "caged-xeno-3-dna-polymerase"}, mult=1.33},
    {names={"full-render-xenos", "full-render-xenos-lard", "full-render-xenos-laser", "full-render-xenos-music"}, mult=3},
}

-- Energy multipliers are chosen to keep power consumption values roughly linear between tiers for plant/animal buildings
local building_energy_multipliers = {
    ["assembling-machine"] = {
        {names={"clay-pit-mk01", "clay-pit-mk02", "clay-pit-mk03", "clay-pit-mk04"}, mult=2},
        {names={"soil-extractor-mk01", "soil-extractor-mk02", "soil-extractor-mk03", "soil-extractor-mk04"}, mult=2},
        {names={"micro-mine-mk01", "micro-mine-mk02", "micro-mine-mk03", "micro-mine-mk04"}, mult=3},
        {names={"coalbed-mk01", "coalbed-mk02", "coalbed-mk03", "coalbed-mk04"}, mult=2},
        {names={"hpf", "hpf-mk02", "hpf-mk03", "hpf-mk04"}, mult=1.5},
        {names={"washer", "washer-mk02", "washer-mk03", "washer-mk04"}, mult=1.5},
        {names={"advanced-foundry-mk01", "advanced-foundry-mk02", "advanced-foundry-mk03", "advanced-foundry-mk04"}, mult=1.5},
        {names={"jaw-crusher", "jaw-crusher-mk02", "jaw-crusher-mk03", "jaw-crusher-mk04"}, mult=1.5},
        {names={"automated-screener-mk01", "automated-screener-mk02", "automated-screener-mk03", "automated-screener-mk04"}, mult=1.5},
        ["rhe"] = 3,
        {names={"slaughterhouse-mk01", "slaughterhouse-mk02", "slaughterhouse-mk03", "slaughterhouse-mk04"}, mult=2},
        {names={"plankton-farm", "plankton-farm-mk02", "plankton-farm-mk03", "plankton-farm-mk04"}, mult=2},
        ["moss-farm-mk01"] = 4,
        ["sap-extractor-mk01"] = 4,
        ["fwf-mk01"] = 2,
        ["fawogae-plantation-mk01"] = 3,
        ["moondrop-greenhouse-mk01"] = 4,
        ["moondrop-greenhouse-mk02"] = 2.2,
        ["moondrop-greenhouse-mk03"] = 1.3,
        ["seaweed-crop-mk01"] = 4,
        ["seaweed-crop-mk02"] = 1.25,
        ["seaweed-crop-mk03"] = 1.07,
        ["vrauks-paddock-mk01"] = 4,
        ["vrauks-paddock-mk02"] = 1.66,
        ["vrauks-paddock-mk03"] = 1.16,
        {names={"fish-farm-mk01", "fish-farm-mk01-turd"}, mult=1.5},
        {names={"fish-farm-mk02", "fish-farm-mk02-turd"}, mult=1.16},
        {names={"fish-farm-mk03", "fish-farm-mk03-turd"}, mult=1.07},
        ["prandium-lab-mk01"] = 2,
        ["prandium-lab-mk02"] = 1.33,
        ["prandium-lab-mk03"] = 1.1,
        ["ralesia-plantation-mk01"] = 4,
        ["ralesia-plantation-mk02"] = 1.2,
        ["ralesia-plantation-mk03"] = 1.07,
        ["tuuphra-plantation-mk01"] = 3,
        ["tuuphra-plantation-mk02"] = 2,
        ["tuuphra-plantation-mk03"] = 1.25,
        ["arqad-hive-mk01"] = 1.5,
        ["arqad-hive-mk02"] = 1.15,
        ["arqad-hive-mk03"] = 1.05,
        ["ez-ranch-mk01"] = 2,
        ["ez-ranch-mk02"] = 1.25,
        ["ez-ranch-mk03"] = 1.05,
        ["zipir-reef-mk01"] = 2,
        ["zipir-reef-mk02"] = 1.1,
        ["zipir-reef-mk03"] = 1.05,
        ["xyhiphoe-pool-mk01"] = 2,
        ["xyhiphoe-pool-mk02"] = 1.33,
        ["xyhiphoe-pool-mk03"] = 1.1,
        ["yotoi-aloe-orchard-mk01"] = 3,
        ["yotoi-aloe-orchard-mk02"] = 1.66,
        ["yotoi-aloe-orchard-mk03"] = 1.2,
        ["rennea-plantation-mk01"] = 5,
        ["rennea-plantation-mk02"] = 2.35,
        ["rennea-plantation-mk03"] = 1.45,
        ["grods-swamp-mk01"] = 2,
        ["grods-swamp-mk02"] = 1.33,
        ["grods-swamp-mk03"] = 1.1,
        ["cadaveric-arum-mk01"] = 4,
        ["cadaveric-arum-mk02"] = 2.4,
        ["cadaveric-arum-mk03"] = 1.55,
        ["phagnot-corral-mk01"] = 2,
        ["phagnot-corral-mk02"] = 1.33,
        ["phagnot-corral-mk03"] = 1.1,
        ["arthurian-pen-mk01"] = 1.5,
        ["arthurian-pen-mk02"] = 1.25,
        ["arthurian-pen-mk03"] = 1.07,
        ["dhilmos-pool-mk01"] = 2,
        ["dhilmos-pool-mk02"] = 1.33,
        ["dhilmos-pool-mk03"] = 1.1,
        ["dingrits-pack-mk01"] = 2,
        ["dingrits-pack-mk02"] = 1.33,
        ["dingrits-pack-mk03"] = 1.1,
        ["vonix-den-mk01"] = 2,
        ["vonix-den-mk02"] = 1.33,
        ["vonix-den-mk03"] = 1.1,
        ["zungror-lair-mk01"] = 2,
        ["zungror-lair-mk02"] = 1.55,
        ["zungror-lair-mk03"] = 1.33,
        ["xenopen-mk01"] = 2,
        ["xenopen-mk02"] = 1.66,
        ["xenopen-mk03"] = 1.16,
    },
}

--- Multiplies the speed of a recipe and adds the multiplier to its description
function multiply_recipe_speed(name, mult)
    local recipe = data.raw.recipe[name]
    if recipe then
        if recipe.energy_required then
            recipe.energy_required = recipe.energy_required / mult
            py.add_to_description("recipe", recipe, {"description.pysimple-speed-mult", "x"..mult})
        end
    elseif debug_errors then
        error("invalid recipe name: "..name)
    end
end

--- Multiplies the power consumption of an entity and adds the multiplier to its description
function multiply_entity_consumption(kind, name, mult)
    local building = data.raw[kind][name]
    if building then
        local energy_value = util.parse_energy(building.energy_usage) * 60
        if energy_value then
            building.energy_usage = energy_value * mult .. "W"
            py.add_to_description("entity", building, {"description.pysimple-consumption-mult", "x"..mult})
        end
    elseif debug_errors then
        error("invalid entity name: "..name)
    end
end

-- Increases speeds for recipes and energy consumption for buildings according to the above tables
if settings.startup["pysimple-faster-recipes"].value then
    for name,info in pairs(recipe_speed_multipliers) do
        if type(info) == "number" then
            multiply_recipe_speed(name, info)
        else
            for _,name in pairs(info.names) do
                multiply_recipe_speed(name, info.mult)
            end
        end
    end
    for kind,buildings in pairs(building_energy_multipliers) do
        for name,info in pairs(buildings) do
            if type(info) == "number" then
                multiply_entity_consumption(kind, name, info)
            else
                for _,name in pairs(info.names) do
                    multiply_entity_consumption(kind, name, info.mult)
                end
            end
        end
    end
end

--- Adds a string to a recipe description - used for exceptional cases when the above functions don't work properly
function add_to_description(recipe, localised_string)
    if data.raw.recipe[recipe] then
        data.raw.recipe[recipe].localised_description = {"?", {"", {"recipe-description." .. recipe}, "\n", localised_string}, localised_string }
    end
end
add_to_description("purest-nitrogen-gas", {"description.pysimple-speed-mult", "x"..recipe_speed_multipliers["purest-nitrogen-gas"]})
