--- sort-recipe-unlocks.lua

local tech_unlocks = {
    ["automation-science-pack"] = {"flora-collector-mk01", "soil-extractor-mk01", "soil", "wpu-mk01", "empty-planter-box", "planter-box", "automation-science-pack", "lab"},
    ["coal-processing-1"] = {"distilator", "distilled-raw-coal", "coal-gas", "coal-gas-from-coke", "coal-gas-from-wood", "py-gas-vent", "tailings-pond", "iron-oxide-smelting"},
    ["ceramic"] = {"clay-pit-mk01", "clay", "ceramic", "electronics-factory-mk01", "inductor1"},
    ["crusher"] = {"jaw-crusher", "bricks-to-stone", "stone-to-gravel", "gravel-to-sand", "grade-1-iron-crush", "low-grade-smelting-iron"},
    ["concrete"] = {"hpf", "lime", "concrete", "hazard-concrete", "refined-concrete", "refined-hazard-concrete"},
    ["tar-processing"] = {"tar-processing-unit", "tar-refining", "tar-refining-tops", "pitch-refining", "light-oil-aromatics", "stone-brick-2", "anthracene-gasoline-cracking", "quenching-tower", "tar-quenching", "tar-distilation", "sand-brick"},
    ["acetylene"] = {"calcium-carbide", "gasifier", "acetylene"},
    ["creosote"] = {"treated-wood", "small-electric-pole-2", "carbolic-oil-creosote", "naphthalene-oil-creosote", "anthracene-oil-creosote"},
    ["moondrop"] = {"moondrop-codex", "moondrop-sample", "moondrop-seeds", "moondrop-greenhouse-mk01", "moondrop-1", "methane-co2", "methanal"},
    ["sap-mk01"] = {"sap-seeds", "sap-tree", "sap-extractor-mk01", "sap-01"},
    ["wood-processing"] = {"wood-seeds", "wood-seedling", "tree", "fwf-mk01", "log1", "log2", "log3", "fiber-01", "cellulose-00"},
    ["fluid-pressurization"] = {"vacuum-pump-mk01", "vacuum", "graphite", "vacuum-tube", "saline-water", "gravel-saline-water"},
    ["electronics"] = {"battery-mk00", "capacitor1", "resistor1", "pulp-mill-mk01", "formica", "pcb-factory-mk01", "pcb1", "chipshooter-mk01", "electronic-circuit"},
    ["plastics"] = {"biofactory-mk01", "aromatics-to-plastic", "empty-jerry-can"},
    ["compost"] = {"biomass-cooking", "flue-gas-1", "flue-gas-3", "compost-plant-mk01"},
    ["py-storage-tanks"] = {"py-tank-3000", "py-tank-1000", "py-tank-1500", "storage-tank", "py-tank-4000", "py-tank-7000", "py-tank-5000", "py-tank-6500", "py-tank-8000", "py-tank-9000", "py-tank-10000"},
    ["basic-substrate"] = {"micro-mine-mk01", "petri-dish-bacteria", "fawogae-substrate", "sand-void-glass"},
    ["copper-mk01"] = {"automated-screener-mk01", "grade-2-copper", "grade-1-copper-crush", "copper-plate-4"},
    ["scrude"] = {"reformer-mk01", "scrude-refining", "olefin-plant", "heavy-oil-to-kerosene"},
    ["vrauks"] = {"vrauks-codex", "vrauks", "vrauks-cocoon-1", "vrauks-paddock-mk01", "vrauks-1", "caged-vrauks", "uncaged-vrauks"},
    ["rendering"] = {"slaughterhouse-mk01", "full-render-vrauks"},

    ["py-science-pack-mk01"] = {"stopper", "flask", "research-center-mk01", "py-science-pack-1"},
    ["crusher-2"] = {"secondary-crusher-mk01", "limestone-void"},
    ["fluid-processing-machines-1"] = {"evaporator", "tailings-dust", "extract-sulfur"},
    ["military"] = {"submachine-gun", "shotgun", "gun-powder", "shotgun-shell", "firearm-magazine"},
    ["boron"] = {"borax-washing", "diborane", "boric-acid", "boron-trioxide"},
    ["electric-mining-drill"] = {"electric-mining-drill", "fluid-drill-mk02"},
    ["geothermal-power-mk01"] = {"geothermal-plant-mk01", "geo-he-00"},
    ["antimony-mk01"] = {"antimony-drill-mk01", "sb-grade-01", "sb-grade-02", "sb-grade-03", "sb-grade-04", "sb-oxide-01", "pbsb-alloy"},
    ["nexelit-mk01"] = {"dino-dig-site", "digosaurus", "nexelit-ore-1", "clean-nexelit", "nexelit-plate-2"},
    ["casting-mk01"] = {"sand-casting", "casting-unit-mk01"},
    ["separation"] = {"soil-separation-2", "classifier", "coarse-classification", "sand-classification"},
    ["mycology-mk01"] = {"ground-sample01", "spore-collector-mk01"},
    ["fawogae-mk01"] = {"fawogae-codex", "earth-shroom-sample", "fawogae-spore", "fawogae-sample", "fawogae-plantation-mk01", "fawogae-1", "coal-fawogae"},
    ["vrauks-mk02"] = {"vrauks-food-01", "vrauks-cocoon-2", "vrauks-2", "vrauks-mk02", "vrauks-mk02-cocoon", "vrauks-mk02-breeder"},
    ["rubber"] = {"carbon-black", "polybutadiene", "rubber-01", "stopper-2", "belt", "long-handed-inserter", "transport-belt-2", "engine-unit-2"},
    ["microbiology-mk01"] = {"zogna-bacteria", "plankton-farm", "phytoplankton", "jerky-to-plankton", "biocrud-reprocessing"},
    ["ralesia"] = {"ralesia-codex", "earth-flower-sample", "ralesia-sample", "ralesia-seeds", "ralesia-plantation-mk01", "ralesia-1"},
    ["auog"] = {"auog-codex", "earth-bear-sample", "auog", "auog-food-01", "auog-pup-breeding-1", "auog-pup-breeding-2", "auog-paddock-mk01", "auog-maturing-1", "auog-maturing-2", "auog-pooping-1", "auog-pooping-2", "caged-auog", "uncaged-auog", "full-render-auogs"},
    ["melamine"] = {"bio-reactor-mk01", "liquid-manure", "urea-from-liquid-manure", "fbreactor-mk01", "urea-decomposition", "melamine", "melamine-resin"},
    ["starch-mk01"] = {"powdered-ralesia-seeds", "starch", "workers-food"},
    ["machine-components-mk01"] = {"utility-box-mk01", "controler-mk01", "mechanical-parts-01", "electronics-mk01"},
    ["cottongut-mk01"] = {"cottongut-codex", "earth-mouse-sample", "cottongut", "cottongut-food-01", "prandium-lab-mk01", "cottongut-pup-mk01-raising", "cottongut-mature-basic-01", "caged-cottongut-1", "cottongut-cub-1", "full-render-cottongut"},
    ["energy-1"] = {"py-electric-boiler", "salt-mine", "water-saline", "molten-salt"},
    ["cooling-tower-1"] = {"cooling-tower-mk01", "cooling-water"},
    ["coalplant-mk01"] = {"py-coal-powerplant-mk01", "coal-molten-salt-01", "he-01"},
    ["oilplant-mk01"] = {"py-oil-powerplant-mk01", "oil-molten-salt-01", "he-01"},
    ["biomassplant-mk01"] = {"py-biomass-powerplant-mk01", "biomass-molten-salt-01", "he-01"},
    ["wind-mk01"] = {"vawt-turbine-mk01", "vane-mk01", "tower-mk01", "blade-mk01", "rotor-mk01", "yaw-drive-mk01", "nacelle-mk01", "hawt-turbine-mk01"},

    ["logistic-science-pack"] = {"rich-clay", "animal-sample-01", "bone-to-bonemeal-2", "bio-sample01", "alien-sample01", "logistic-science-pack"},
    ["wood-processing-2"] = {"log4", "log5", "log6", "co2-organics", "wood-seeds-mk02", "wood-seedling-mk02", "tree-mk02", "wood-seeds-mk02-breeder"},
    ["pyrite"] = {"pyrite-make", "pyrite-burn"},
    ["drill-head-mk01"] = {"drill-head", "drill-head-2", "drill-head-3"},
    ["filtration"] = {"carbon-filter", "hydrogen-chloride", "hydrogen-chloride-void", "zinc-chloride", "active-carbon", "refsyngas-from-filtered-syngas", "fiber", "micro-fiber", "sand-washing", "filtration-media", "wastewater-recovery", "wastewater-filtration", "fluegas-to-syngas", "fluegas-filtration", "ash3", "ash-bone", "flue-gas-2"},
    ["coal-mk02"] = {"coarse-coal", "coarse-coal-to-coal"},
    ["coke-mk02"] = {"redhot-coke", "quench-redcoke", "biocrud-pyrolysis", "quench-ovengas", "outlet-gas-01", "outlet-gas-02"},
    ["copper-mk02"] = {"grade-3-copper", "copper-rejects-recrush", "grade-4-copper", "classify-low-grade", "wash-coper-low-dust", "low-grade-smelting-copper", "molten-copper-04", "hotair-copper-plate-1"},
    ["tin-mk02"] = {"grade-3-tin", "tin-ore-rejects", "wash-grade-3-tin", "tin-plate-4", "ball-grade-4-tin", "tin-plate-3", "hotair-tin-plate-3", "tar-to-nickel"},
    ["solder-mk02"] = {"molten-solder-0", "molten-solder-1", "solder", "hotair-solder"},
    ["nickel-mk02"] = {"grade-3-nickel", "grade-2-nickel-recrush", "nickel-rejects-recrush", "grade-4-nickel", "molten-nickel-01", "nickel-plate-3", "hotair-nickel-plate-3"},
    ["iron-mk02"] = {"grade-2-iron", "grade-3-iron-processing", "grade-2-crush", "iron-ore-dust", "classify-iron-ore-dust", "iron-slime", "unslimed-iron", "unslimed-iron-2", "molten-iron-06", "hydrocyclone-mk01"},
    ["niobium"] = {"niobium-mine", "niobium-powder", "niobium-dust", "niobium-concentrate", "niobium-complex", "niobium-oxide", "niobium-plate"},
    ["quartz-mk02"] = {"powdered-quartz", "glass-3", "flask-2", "hotair-flask-2", "quartz-tube"},
    ["bioprocessing"] = {"powedered-biomass", "fine-powdered-biomass", "dried-biomass", "bio-oil", "bio-oil-1", "bio-oil-3"},
    ["petroleum-gas-mk01"] = {"natural-gas-01", "natural-gas-refining", "natural-gas-to-syngas", "raw-gas", "refined-natural-gas-to-condensates", "formaldehyde-from-refined-natural-gas", "oil-refining", "low-distillate-to-coal-gas", "low-distillate-to-heavy-oil", "low-distillate-to-btx", "residual-mixture-distillation", "coalbed-gas-to-acidgas", "coalbed-gas-to-syngas", "coalbed-gas-to-co2", "coalbed-gas-to-hydrogen", "upgrader-mk01"},
    ["light-oil-mk01"] = {"lor-mk01", "medium-distillate-to-high-distillate", "high-distillate-condensing", "condensed-distillate-separation", "aromatics-from-napthalene", "crude-from-manure"},
    ["light-oil-mk02"] = {"pressured-hydrogen", "naphtha-2-tall-oil", "aromatics-2-petgas2", "aromatics-2-diesel2", "aromatics-2-diesel", "bio-oil-2", "medium-distillate-to-stripped-distillate", "stripped-distillate-to-gasoline", "stripped-distillate-to-methanol", "stripped-distillate-to-cumene", "stripped-distillate-to-benzene"},
    ["gasplant-mk01"] = {"py-gas-powerplant-mk01", "gas-molten-salt-01", "he-01"},
    ["fluid-separation"] = {"fluid-separator", "tailings-separation", "richdust-separation", "calcinate-bone", "calcinate-separation", "salt-ex", "fluidize-coke", "tall-oil-separation", "petgas-methanol", "coal-slurry", "cloal-slurry-fuel"},
    ["oil-sands"] = {"oil-sand-extractor-mk01", "crush-oil-sand", "oil-sand-slurry", "bitumen-froth", "bitumen", "bitumen-refining", "bitumen-to-sulfur", "bitumen-to-heavy-oil", "bitumen-to-nitrogen", "bitumen-to-nickel", "bitumen-gasification", "quenching-dirty-syngas", "scrubbing-purified-syngas", "hot-syngas-cooldown", "centrifugal-pan-mk01"},
    ["phosphorous-processing"] = {"phosphate-mine", "powdered-phosphate-rock", "phosphorous-acid", "phosphoric-acid", "phosphoric-acid2", "fluorine-gas", "fluorine-to-olefins"},
    ["vanadium-processing"] = {"thickener-mk01", "agitator-mk01", "vanabins", "blue-liquor", "vpulp1", "vpulp2", "vpulp3", "vanadium-pulp-3-void"},
    ["sulfur-processing"] = {"aromatic-organic", "sulfur-mine", "acidgas-2", "gas-separator-mk01", "acidgas", "sulfuric-acid-01", "anthraquinone-from-naphthalene", "hydrogen-peroxide", "sulfuric-acid"},
    ["rare-earth-tech"] = {"ree-mining-drill-mk01", "rare-earth-mine", "crusher-ree", "milling-ree", "ree-float", "rare-earth-beneficiation", "ree-slurry", "ree-solution", "ree-concentrate1", "ree-concentrate3", "centrifugal-pan-mk01", "ree-concentrate2", "reo"},
    ["molybdenum-processing"] = {"mo-mine", "crushing-molybdenite", "milling-molybdenite", "molybdenite-pulp", "molybdenum-concentrate", "molybdenum-pulp", "molybdenum-filtration", "molybdenum-oxide", "molybdenum-plate"},
    ["advanced-mining-facilities"] = {"soda-ash", "industrial-solvent", "hydrocyclone-mk01", "chloride-void-muddy-sludge"},
    ["cobalt-mk01"] = {"mixed-ores", "cobalt-extract", "cobalt-fluoride"},
    ["organic-solvent"] = {"napthalene-solvent", "bone-solvent"},
    ["methanol-processing-1"] = {"methanol-reactor", "methanol-from-syngas", "methane-to-methanol5", "methane-to-methanol6", "acetic-acid", "methanol-void-denitrification", "empty-gas-canister", "fill-methanol-gas-canister", "empty-methanol-gas-canister", "refsyngas-from-meth-canister"},
    ["biotech-mk02"] = {"lard-from-brains", "hcl-from-guts", "fetal-serum-01", "albumin-1", "decalin", "flutec-pp6", "artificial-blood", "arthropod-blood-to-organic-solvent", "formamide", "formic-acid", "ammonia-urea", "subcritical-water-03"},
    ["plastics-mk02"] = {"plastic-from-melamine", "oleochemicals-bioplastic", "plastic-from-casein"},
    ["tuuphra"] = {"tuuphra-codex", "earth-potato-sample", "tuuphra-sample", "tuuphra-seeds", "tuuphra-plantation-mk01", "tuuphra-1"},
    ["ulric"] = {"ulric-codex", "earth-horse-sample", "ulric", "ulric-food-01", "ulric-cub-1", "ulric-corral-mk01", "ulric-1", "ulric-manure-1", "caged-ulric", "uncaged-ulric", "full-render-ulrics"},
    ["arqad"] = {"arqad-codex", "earth-bee-sample", "arqad", "arqad-hive-mk01", "sugar-wax", "empty-honeycomb-2", "hotair-empty-honeycomb-2", "arqad-filled-honeycomb-1", "honey-comb", "arqad-maggots-1", "wax", "empty-comb-2", "arqad-egg-nests-1", "caged-arqad-1", "caged-arqad-2", "arqad-queen-1", "arqad-egg-1", "arqad-egg-2", "full-render-arqads", "empty-comb", "arqad-filled-comb-1", "bitumen-comb", "used-comb-to-residual-mixture", "wax-honeycomb", "honey-wax"},
    ["yaedols"] = {"yaedols-spores", "yaedols-codex", "yaedols-sample", "yaedols-culture-mk01", "yaedols-1", "flavonoids"},
    ["kicalk"] = {"kicalk-codex", "earth-palmtree-sample", "kicalk-sample", "kicalk-seeds", "kicalk-plantation-mk01", "kicalk-1", "kicalk-2", "kicalk-fiber", "coal-dust3", "rich-clay-2"},
    ["korlex"] = {"korlex-codex", "earth-cow-sample", "korlex", "korlex-food-01", "korlex-pup-1", "ez-ranch-mk01", "korlex-1", "barrel-milk", "korlex-milk-1", "milk-barrel", "empty-milk-barrel", "casein-mixture-01", "casein-mixture-02", "casein-pulp-01", "casein-pulp-02", "casein", "caged-korlex", "uncaged-korlex", "full-render-kor"},
    ["water-invertebrates-mk01"] = {"sea-sponge-codex", "earth-sea-sponge-sample", "sea-sponge", "sea-sponge-sprouts", "sponge-culture-mk01", "sea-sponge-1", "sea-sponge-sprouts-processing-01", "sea-sponge-processing-01", "zipir-codex", "earth-crustacean-sample", "xyhiphoe-codex", "xyhiphoe", "xyhiphoe-cub-1", "xyhiphoe-pool-mk01", "xyhiphoe-1", "full-render-xyhiphoe", "arthropod-blood-to-blood", "waste-water-urea"},
    ["zipir"] = {"stone-wool", "stone-wool2", "zipir-eggs-1", "zipir1", "zipir-reef-mk01", "zipir-a-1", "zipir-a-2", "full-render-zipir"},
    ["guar"] = {"guar-sample", "guar-seeds", "guar-gum-plantation", "guar-1", "guar-gum"},
    ["moondrop-mk02"] = {"moondrop-2", "methane-py-fertilizer", "moondrop-mk02", "moondrop-seeds-mk02", "moondrop-mk02-breeder"},
    ["fertilizer-mk02"] = {"fish-hydrolysate", "fertilizer-fish-1", "fertilizer-1", "fertilizer-3"},
    --["microfilters"] = {"fawogae-spore", "yaedols-spores", "navens-spore", "bhoddos-spore"}, -- TODO: Can productivity effects be conveniently differentiated from recipe effects?
    ["hot-air-mk02"] = {"cog-void-soot", "reheat-coke-gas", "warmer-stone-brick-1", "warmer-air-2"},
    ["fuel-production"] = {"olefin", "gasoline", "gasoline-cellulose", "aromatics-to-petgas"},
    ["py-asphalt-mk02"] = {"py-quartz", "bitumen-to-asphalt", "py-coal-tile", "py-iron", "py-steel", "py-aluminium", "py-nexelit"},
    ["py-asphalt-mk03"] = {"py-logo-15tiles", "black-refined-concrete", "brown-refined-concrete", "red-refined-concrete", "orange-refined-concrete", "yellow-refined-concrete", "acid-refined-concrete", "green-refined-concrete", "cyan-refined-concrete", "blue-refined-concrete", "purple-refined-concrete", "pink-refined-concrete"},

    ["rennea"] = {"rennea-codex", "earth-sunflower-sample", "rennea-sample", "rennea-seeds", "rennea-plantation-mk01", "rennea-1", "sporopollenin"},
    ["trits"] = {"trits-codex", "trits", "trits-cub-1", "trits-reef-mk01", "trits-1", "full-render-trit"},
    ["yotoi"] = {"yotoi-codex", "earth-tropical-tree-sample", "yotoi-sample", "yotoi-aloe-orchard-mk01", "yotoi-fruit-1", "yotoi-seeds", "yotoi-1", "yotoi-leaves", "yotoi-fiber"},
    ["cadaveric-arum"] = {"cadaveric-arum-codex", "cadaveric-arum-sample", "cadaveric-arum-seeds", "cadaveric-arum-mk01", "cadaveric-arum-1", "cadaveric-acidgas-01"},
    ["grod"] = {"grod-codex", "earth-jute-sample", "grod-sample", "grod-seeds", "grods-swamp-mk01", "grod-1", "dried-grods", "dried-grods-02", "bedding"},
    ["mukmoux"] = {"oleo-gasification", "bone-fat", "glycerol2", "mukmoux-codex", "mukmoux", "mukmoux-food-01", "mukmoux-calf-1", "mukmoux-pasture-mk01", "mukmoux-1", "mukmoux-manure-1", "caged-mukmoux", "uncaged-mukmoux", "full-render-mukmoux"},
    ["navens"] = {"navens-spore", "navens-codex", "navens-sample", "navens-culture-mk01", "navens-1", "naven-coal"},
    ["bhoddos"] = {"bhoddos-codex", "bhoddos-sample", "bhoddos-culture-mk01", "bhoddos-1"},
    ["phagnot"] = {"phagnot-codex", "earth-giraffe-sample", "phagnot", "phagnot-food-01", "phagnot-cub-1", "phagnot-corral-mk01", "phagnot-1", "phagnot-mature-basic-01", "caged-phagnot", "uncaged-phagnot", "full-render-phagnots", "gas-bladder-to-co2"},
    ["cellulose-mk02"] = {"yotoi-cellulose", "lignin", "lignin-to-aromatics", "concrete-02", "filtration-media-3", "cellulose-gasification"},
    ["phenol"] = {"phenol-02", "phenol-3", "melamine-2"},
    ["kevlar"] = {"tpa", "ppd", "kevlar"},
    ["aramid"] = {"nmf-mk01", "aramid", "lead-container"},
    ["semiconductor-doping"] = {"etching", "silicon-wafer", "light-n", "heavy-n", "zinc-acetate", "p-dope"},
    ["integrated-circuits-01"] = {"bakelite", "phenolicboard", "pcb2", "crude-cermet", "cermet", "microchip", "diode", "transistor", "ceramic-2"},
    ["basic-elecronics"] = {"methane-methanal", "ferrite", "inductor2", "capacitor2", "resistor2", "nisi", "mosfet", "advanced-circuit"},
    ["fine-electronics"] = {"cladding", "glass-core", "hotair-glass-core", "cladded-core", "copper-coating", "kevlar-coating", "nbfe-coating", "optical-fiber"},
    ["uranium-processing"] = {"uranium-mining-drill", "grade-1-u", "grade-1-u-recrush", "grade-2-u-crush", "u-pulp-01", "u-pulp-02", "u-pulp-03", "u-rich-pulp", "split-yellowcake", "uranium-fuel-cell", "fuel-cell-dissolve", "antimony-phosphate", "plutonium-oxidation", "plutonium", "purex-antimony-void", "particle-accelerator-mk01", "plutonium-seperation", "plutonium-fuel-cell", "plutonium-fuel-reprocessing", "nuclear-reactor", "fuelrod-mk01-1", "steam-heating"},
    -- TODO: Reorder unlocks for remaining stage 4 technologies and beyond
    ["chemical-science-pack"] = {"nuclear-sample", "chemical-science-pack"},
    ["arthurian"] = {"arthurian-codex", "earth-lizard-sample", "arthurian", "arthurian-egg-1", "arthurian-egg-incubation-01", "arthurian-pen-mk01", "arthurian-maturing-1", "caged-arthurian", "uncaged-arthurian", "full-render-arthurian"},
    ["cridren"] = {"cridren-codex", "earth-venus-fly-sample", "cridren-sample", "cridren-seeds", "cridren-enclosure-mk01", "cridren-1", "adrenal-cortex"},
    ["dingrits"] = {"dingrits-codex", "earth-wolf-sample", "dingrits", "dingrits-food-01", "dingrits-cub-1", "dingrits-pack-mk01", "dingrits-1", "caged-dingrits", "uncaged-dingrits", "full-render-dingrits"},
    ["dhilmos"] = {"dhilmos-codex", "dhilmos", "dhilmos-egg-1", "dhilmos-pool-mk01", "dhilmos-hatching-1", "dhilmos-1", "full-render-dhilmoss"},
    ["scrondrix"] = {"scrondrix-codex", "earth-roadrunner-sample", "scrondrix", "Scrondrix-cub-1", "scrondrix-pen-mk01", "Scrondrix-1", "Scrondrix-Manure-1", "caged-scrondrix", "uncaged-scrondrix", "full-render-scrondrixs"},
    ["kmauts"] = {"kmauts-codex", "kmauts", "kmauts-cub-1", "kmauts-enclosure-mk01", "kmauts-1", "caged-kmauts", "uncaged-kmauts", "full-render-kmauts", "serine", "bacteria-1", "methane-from-liquid-manure"},
    ["phadai"] = {"phadai-codex", "earth-tiger-sample", "phadai", "phadai-food-01", "phadai-pup-1", "phadai-pup-2", "phadai-enclosure-mk01", "phadai-1", "Phadai-Dance-Dance-Revolution-1", "phadai-recharge-1", "caged-phadai", "uncaged-phadai", "full-render-phadais"},
    ["simik-mk01"] = {"simik-codex", "strorix-unknown-sample", "simik", "simik-food-01", "simik-cub-1", "simik-den-mk01", "caged-simik-1", "simik-poop-1", "caged-simik", "uncaged-simik", "full-render-simik", "simik-blood-to-tar"},
    ["numal-mk01"] = {"numal-codex", "numal", "numal-egg-1", "numal-reef-mk01", "numal-raising-1", "full-render-num"},
    ["vonix"] = {"vonix-codex", "vonix", "vonix-cub-1", "vonix-grow-01", "vonix-den-mk01", "vonix-raising-1", "full-render-vonix"},
    ["zungror"] = {"zungror-codex", "earth-goat-sample", "earth-spider-sample", "zungror", "zungror-cocoon-1", "zungror-lair-mk01", "zungror-raising-1", "caged-zungror", "uncaged-zungror", "full-render-zun"},
    ["xeno"] = {"xeno-codex", "xeno", "xeno-egg-1", "xenopen-mk01", "caged-xeno-1", "caged-xeno", "uncaged-xeno", "full-render-xenos"},
    ["schrodinger-antelope"] = {"antelope-codex", "earth-antelope-sample", "antelope", "cage-antelope", "caged-antelope", "uncage-antelope", "antelope-enclosure-mk01", "caged-antelope-1", "caged-antelope-2", "caged-antelope-3", "caged-antelope-4", "caged-antelope-5", "caged-antelope-6", "caged-antelope-7", "caged-antelope-8", "full-render-antelope"},
}

if (settings.startup["pysimple-descriptions"].value and not mods["PyBlock"]) or technology_adjustments ~= "1" then
    if not (settings.startup["py-tank-adjust"].value or settings.startup["pysimple-storage-tanks"].value) then tech_unlocks["py-storage-tanks"] = nil end
    -- reorders recipe unlocks by priority - recipes which need to be used first will be listed first
    for tech,unlocks in pairs(tech_unlocks) do
        if data.raw.technology[tech] then
            local use_index = true
            for i,unlock in pairs(unlocks) do
                if use_index then
                    local added = add_unlock(unlock, tech, tech, i)
                    if not added then use_index = false end -- prevents issues due to missing recipes such as those related to "decay" which results in tables of different sizes
                else
                    add_unlock(unlock, tech, tech)
                end
            end
        end
    end
end